apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: default
data:
  GCLOUD_PROJECT: visa-gnib-notifier
  MAILJET_API_KEY: e6e5fd4838b27c6e5cfe5324597b9a05
  MAILJET_SECRET_KEY: c91ca692e3cc27bd1093f5cd086e649fâ€¨
  MAILJET_SENDER: notification@visa-gnib.info
  SQLALCHEMY_DATABASE_URI: mysql://root:UbV1udXNzso3@35.189.193.111/main
  CREDENTIALS: |
    {
      "type": "service_account",
      "project_id": "visa-gnib-notifier",
      "private_key_id": "92ac65f2d7fc479d76e38d317a3e906e998f36d0",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOS9ZIZDzA4VEE\nHsCndpZe0yy00Fa97Q3mP/9wOFuPHf+9w2kGstpV0heqso3im882fiRvKBrOGDc2\n3PqUQJVIu75b7cErlB6eslNBM72ZA0B6+RBwK2rezGN1JLn5ICXBCE4x2YukskKd\nkwttPW1sZxIobyHvpk1wkBrUEDuooJwOdwTvDpHi031CBZFLOzdIyVZCBNLc7QqY\n0clJEEETg1IdQ/0hYebsZalCde+EpErXdS4n2HgIGVtRgl1HYaf9Iw1QLJR9flTb\ngXzwrCaBqsfot37zKNwRU1RSYil6XwJYuJeVkR92bS0U8cPE6VzN6XpACEeWTu9y\nLQZG99qPAgMBAAECggEAZIao/zK1Nio1n+PabmBHqyKNfPiu5DMBXGtgLo+P8kAk\nkJSJ98UsxrgvZzNGF6BkS4IRgAcTdM1xDm+FPbvw4vX1r3c+c91kRGHSVwn/AHKI\nt8PpgjduBu6jIoDIjQDg1N0WuYzwUsu40W9HmK5fxXy+aOyqpUytHMZkBGV6pNLq\nEpvwkz3O8wUevBvmCWpFmVwQsbJ1QLSTTWOOOet0pqoXAsVT+xe7dgOCoq84akOp\nlm12sTN3pJD/13HE1leQLTUu/WgU7qKgHJBbynoZImm652tw7qOuYYxnItShv5AO\nQAbw2T/Q8mH+TQLUZjyjE2gAmF/l7ay0h+t+MBoxwQKBgQD68DbVPahuP+5TeUtJ\nf/5pqjxrQmuAn1gCm0XXKB3bEXmsfS1mDsxiy0a3dLxkWaxyk4q4NOMGE6Ehb7Ij\n3z9BrzNkZeEsr4TiTvSDzZRwdVddkAfXbbM2UWGq3+IZoYiKTnyKxcsx1aoiXTYK\nwKs41F/FoaijMzRczzyLouM2TwKBgQDSdRoIK/65qPqXpc/tSfl4q8q1x/QayZf/\nQ96afwsHDTXUpCdamW4dxOMfbhXNACtUajFOe/QgsuudjCPKWZwiAjRjhtFFyUnb\nBaevJzzkp2xtYyodSTqwPr7MQ3muL0Lz/DJeFf5N5oLNi98w4Ky8qH1rt3jlBVRo\nYNiQ5aRHwQKBgQCZ0hf6nQIbGutPleGVm3TrdqP0p9FYFdUQO/gSzI+Ikuy/1De5\nAMc+pBakLFWzOdjgnxqAkkK7ndq+sUZEgPu4mtno6B6gkrLlOrrd9G3ShctZGgoE\nf0VEvZwd74Ecbw1Qoo3rTxWgZbYVvId9Dd+nRV+zuMWzzJaDcbFOcznONwKBgAHV\naVum3npJoZ1OoYgku9q0THjW/CZ7mSptMfRQpQzzrYNjxsAAVDhILd5pPCFkHfyH\nTFStucvLI0hlHy61JyoYsNIpK4ubHFyfKP3arqojV0uAsK4+pBdDBLCM6fN9j+zG\nRr4RHP0axAr8a/5mBrtCEI2utIvyRvD93wUsKwlBAoGACB01q7WRJbYyhItAkjZ0\n/0qEgb76wvnnUVdV3x+RihFxBPgG8FkIzxoy0fvDS4GIIJJsJXLrHskvNHDf4Lzh\n4Ocn2A6/V9IeMGDNUr3rngegMoJBW1eaDcLsI35M+m29CT2pYyWS4Pc33fBbkKNJ\nenuDPYQOTEicdEsmJs3U2Zc=\n-----END PRIVATE KEY-----\n",
      "client_email": "1042211171184-compute@developer.gserviceaccount.com",
      "client_id": "107628484810466137414",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://accounts.google.com/o/oauth2/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/1042211171184-compute%40developer.gserviceaccount.com"
    }
